tmdb2world = {
    "Andorra": None,
    "United Arab Emirates": "United Arab Emirates",
    "Afghanistan": "Afghanistan",
    "Antigua and Barbuda": None,
    "Anguilla": None,
    "Albania": "Albania",
    "Armenia": "Armenia",
    "Netherlands Antilles": None,
    "Angola": "Angola",
    "Antarctica": "Antarctica",
    "Argentina": "Argentina",
    "American Samoa": None,
    "Austria": "Austria",
    "Australia": "Australia",
    "Aruba": None,
    "Azerbaijan": "Azerbaijan",
    "Bosnia and Herzegovina": "Bosnia and Herzegovina",
    "Barbados": None,
    "Bangladesh": "Bangladesh",
    "Belgium": "Belgium",
    "Burkina Faso": "Burkina Faso",
    "Bulgaria": "Bulgaria",
    "Bahrain": None,
    "Burundi": "Burundi",
    "Benin": "Benin",
    "Bermuda": None,
    "Brunei Darussalam": "Brunei",
    "Bolivia": "Bolivia",
    "Brazil": "Brazil",
    "Bahamas": "The Bahamas",
    "Bhutan": "Bhutan",
    "Burma": "Myanmar",
    "Bouvet Island": None,
    "Botswana": "Botswana",
    "Belarus": "Belarus",
    "Belize": "Belize",
    "Canada": "Canada",
    "Cocos Islands": None,
    "Congo": "Republic of the Congo",
    "Central African Republic": "Central African Republic",
    "Switzerland": "Switzerland",
    "Cote D'Ivoire": "Ivory Coast",
    "Cook Islands": None,
    "Chile": "Chile",
    "Cameroon": "Cameroon",
    "China": "China",
    "Colombia": "Colombia",
    "Costa Rica": "Costa Rica",
    "Serbia and Montenegro": None,
    "Cuba": "Cuba",
    "Cape Verde": None,
    "Christmas Island": None,
    "Cyprus": "Cyprus",
    "Czech Republic": "Czech Republic",
    "Germany": "Germany",
    "Djibouti": "Djibouti",
    "Denmark": "Denmark",
    "Dominica": None,
    "Dominican Republic": "Dominican Republic",
    "Algeria": "Algeria",
    "Ecuador": "Ecuador",
    "Estonia": "Estonia",
    "Egypt": "Egypt",
    "Western Sahara": "Western Sahara",
    "Eritrea": "Eritrea",
    "Spain": "Spain",
    "Ethiopia": "Ethiopia",
    "Finland": "Finland",
    "Fiji": "Fiji",
    "Falkland Islands": "Falkland Islands",
    "Micronesia": None,
    "Faeroe Islands": None,
    "France": "France",
    "Gabon": "Gabon",
    "United Kingdom": "England",
    "Grenada": None,
    "Georgia": "Georgia",
    "French Guiana": None,
    "Ghana": "Ghana",
    "Gibraltar": None,
    "Greenland": "Greenland",
    "Gambia": "Gambia",
    "Guinea": "Guinea",
    "Guadaloupe": None,
    "Equatorial Guinea": "Equatorial Guinea",
    "Greece": "Greece",
    "South Georgia and the South Sandwich Islands": None,
    "Guatemala": "Guatemala",
    "Guam": None,
    "Guinea-Bissau": "Guinea Bissau",
    "Guyana": "Guyana",
    "Hong Kong": None,
    "Heard and McDonald Islands": None,
    "Honduras": "Honduras",
    "Croatia": "Croatia",
    "Haiti": "Haiti",
    "Hungary": "Hungary",
    "Indonesia": "Indonesia",
    "Ireland": "Ireland",
    "Israel": "Israel",
    "India": "India",
    "British Indian Ocean Territory": None,
    "Iraq": "Iraq",
    "Iran": "Iran",
    "Iceland": "Iceland",
    "Italy": "Italy",
    "Jamaica": "Jamaica",
    "Jordan": "Jordan",
    "Japan": "Japan",
    "Kenya": "Kenya",
    "Kyrgyz Republic": "Kyrgyzstan",
    "Cambodia": "Cambodia",
    "Kiribati": None,
    "Comoros": None,
    "St. Kitts and Nevis": None,
    "North Korea": "North Korea",
    "South Korea": "South Korea",
    "Kuwait": "Kuwait",
    "Cayman Islands": None,
    "Kazakhstan": "Kazakhstan",
    "Lao People's Democratic Republic": "Laos",
    "Lebanon": "Lebanon",
    "St. Lucia": None,
    "Liechtenstein": None,
    "Sri Lanka": "Sri Lanka",
    "Liberia": "Liberia",
    "Lesotho": "Lesotho",
    "Lithuania": "Lithuania",
    "Luxembourg": "Luxembourg",
    "Latvia": "Latvia",
    "Libyan Arab Jamahiriya": "Libya",
    "Morocco": "Morocco",
    "Monaco": None,
    "Moldova": "Moldova",
    "Montenegro": "Montenegro",
    "Madagascar": "Madagascar",
    "Marshall Islands": None,
    "Macedonia": "Macedonia",
    "Mali": "Mali",
    "Myanmar": "Myanmar",
    "Mongolia": "Mongolia",
    "Macao": None,
    "Northern Mariana Islands": None,
    "Martinique": None,
    "Mauritania": "Mauritania",
    "Montserrat": None,
    "Malta": None,
    "Mauritius": None,
    "Maldives": None,
    "Malawi": "Malawi",
    "Mexico": "Mexico",
    "Malaysia": "Malaysia",
    "Mozambique": "Mozambique",
    "Namibia": "Namibia",
    "New Caledonia": "New Caledonia",
    "Niger": "Niger",
    "Norfolk Island": None,
    "Nigeria": "Nigeria",
    "Nicaragua": "Nicaragua",
    "Netherlands": "Netherlands",
    "Norway": "Norway",
    "Nepal": "Nepal",
    "Nauru": None,
    "Niue": None,
    "New Zealand": "New Zealand",
    "Oman": "Oman",
    "Panama": "Panama",
    "Peru": "Peru",
    "French Polynesia": None,
    "Papua New Guinea": "Papua New Guinea",
    "Philippines": "Philippines",
    "Pakistan": "Pakistan",
    "Poland": "Poland",
    "St. Pierre and Miquelon": None,
    "Pitcairn Island": None,
    "Puerto Rico": "Puerto Rico",
    "Palestinian Territory": "West Bank",
    "Portugal": "Portugal",
    "Palau": None,
    "Paraguay": "Paraguay",
    "Qatar": "Qatar",
    "Reunion": None,
    "Romania": "Romania",
    "Serbia": "Republic of Serbia",
    "Russia": "Russia",
    "Rwanda": "Rwanda",
    "Saudi Arabia": "Saudi Arabia",
    "Solomon Islands": "Solomon Islands",
    "Seychelles": None,
    "Sudan": "Sudan",
    "Sweden": "Sweden",
    "Singapore": None,
    "St. Helena": None,
    "Slovenia": "Slovenia",
    "Svalbard & Jan Mayen Islands": None,
    "Slovakia": "Slovakia",
    "Sierra Leone": "Sierra Leone",
    "San Marino": None,
    "Senegal": "Senegal",
    "Somalia": "Somalia",
    "Suriname": "Suriname",
    "South Sudan": "South Sudan",
    "Sao Tome and Principe": None,
    "Soviet Union": None,
    "El Salvador": "El Salvador",
    "Syrian Arab Republic": "Syria",
    "Swaziland": "Swaziland",
    "Turks and Caicos Islands": None,
    "Chad": "Chad",
    "French Southern Territories": "French Southern and Antarctic Lands",
    "Togo": "Togo",
    "Thailand": "Thailand",
    "Tajikistan": "Tajikistan",
    "Tokelau": None,
    "Timor-Leste": "East Timor",
    "Turkmenistan": "Turkmenistan",
    "Tunisia": "Tunisia",
    "Tonga": None,
    "East Timor": "East Timor",
    "Turkey": "Turkey",
    "Trinidad and Tobago": "Trinidad and Tobago",
    "Tuvalu": None,
    "Taiwan": "Taiwan",
    "Tanzania": "United Republic of Tanzania",
    "Ukraine": "Ukraine",
    "Uganda": "Uganda",
    "United States Minor Outlying Islands": None,
    "United States of America": "USA",
    "Uruguay": "Uruguay",
    "Uzbekistan": "Uzbekistan",
    "Holy See": None,
    "St. Vincent and the Grenadines": None,
    "Venezuela": "Venezuela",
    "British Virgin Islands": None,
    "US Virgin Islands": None,
    "Vietnam": "Vietnam",
    "Vanuatu": "Vanuatu",
    "Wallis and Futuna Islands": None,
    "Samoa": None,
    "Czechoslovakia": None,
    "East Germany": None,
    "Northern Ireland": None,
    "Kosovo": "Kosovo",
    "Yemen": "Yemen",
    "Mayotte": None,
    "Yugoslavia": None,
    "South Africa": "South Africa",
    "Zambia": "Zambia",
    "Zaire": "Democratic Republic of the Congo",
    "Zimbabwe": "Zimbabwe"
  }

world2tmdb={'United Arab Emirates': 'United Arab Emirates', 'Afghanistan': 'Afghanistan', 'Albania': 'Albania', 'Armenia': 'Armenia', 'Angola': 'Angola', 'Antarctica': 'Antarctica', 'Argentina': 'Argentina', 'Austria': 'Austria', 'Australia': 'Australia', 'Azerbaijan': 'Azerbaijan', 'Bosnia and Herzegovina': 'Bosnia and Herzegovina', 'Bangladesh': 'Bangladesh', 'Belgium': 'Belgium', 'Burkina Faso': 'Burkina Faso', 'Bulgaria': 'Bulgaria', 'Burundi': 'Burundi', 'Benin': 'Benin', 'Brunei': 'Brunei Darussalam', 'Bolivia': 'Bolivia', 'Brazil': 'Brazil', 'The Bahamas': 'Bahamas', 'Bhutan': 'Bhutan', 'Myanmar': 'Myanmar', 'Botswana': 'Botswana', 'Belarus': 'Belarus', 'Belize': 'Belize', 'Canada': 'Canada', 'Republic of the Congo': 'Congo', 'Central African Republic': 'Central African Republic', 'Switzerland': 'Switzerland', 'Ivory Coast': "Cote D'Ivoire", 'Chile': 'Chile', 'Cameroon': 'Cameroon', 'China': 'China', 'Colombia': 'Colombia', 'Costa Rica': 'Costa Rica', 'Cuba': 'Cuba', 'Cyprus': 'Cyprus', 'Czech Republic': 'Czech Republic', 'Germany': 'Germany', 'Djibouti': 'Djibouti', 'Denmark': 'Denmark', 'Dominican Republic': 'Dominican Republic', 'Algeria': 'Algeria', 'Ecuador': 'Ecuador', 'Estonia': 'Estonia', 'Egypt': 'Egypt', 'Western Sahara': 'Western Sahara', 'Eritrea': 'Eritrea', 'Spain': 'Spain', 'Ethiopia': 'Ethiopia', 'Finland': 'Finland', 'Fiji': 'Fiji', 'Falkland Islands': 'Falkland Islands', 'France': 'France', 'Gabon': 'Gabon', 'England': 'United Kingdom', 'Georgia': 'Georgia', 'Ghana': 'Ghana', 'Greenland': 'Greenland', 'Gambia': 'Gambia', 'Guinea': 'Guinea', 'Equatorial Guinea': 'Equatorial Guinea', 'Greece': 'Greece', 'Guatemala': 'Guatemala', 'Guinea Bissau': 'Guinea-Bissau', 'Guyana': 'Guyana', 'Honduras': 'Honduras', 'Croatia': 'Croatia', 'Haiti': 'Haiti', 'Hungary': 'Hungary', 'Indonesia': 'Indonesia', 'Ireland': 'Ireland', 'Israel': 'Israel', 'India': 'India', 'Iraq': 'Iraq', 'Iran': 'Iran', 'Iceland': 'Iceland', 'Italy': 'Italy', 'Jamaica': 'Jamaica', 'Jordan': 'Jordan', 'Japan': 'Japan', 'Kenya': 'Kenya', 'Kyrgyzstan': 'Kyrgyz Republic', 'Cambodia': 'Cambodia', 'North Korea': 'North Korea', 'South Korea': 'South Korea', 'Kuwait': 'Kuwait', 'Kazakhstan': 'Kazakhstan', 'Laos': "Lao People's Democratic Republic", 'Lebanon': 'Lebanon', 'Sri Lanka': 'Sri Lanka', 'Liberia': 'Liberia', 'Lesotho': 'Lesotho', 'Lithuania': 'Lithuania', 'Luxembourg': 'Luxembourg', 'Latvia': 'Latvia', 'Libya': 'Libyan Arab Jamahiriya', 'Morocco': 'Morocco', 'Moldova': 'Moldova', 'Montenegro': 'Montenegro', 'Madagascar': 'Madagascar', 'Macedonia': 'Macedonia', 'Mali': 'Mali', 'Mongolia': 'Mongolia', 'Mauritania': 'Mauritania', 'Malawi': 'Malawi', 'Mexico': 'Mexico', 'Malaysia': 'Malaysia', 'Mozambique': 'Mozambique', 'Namibia': 'Namibia', 'New Caledonia': 'New Caledonia', 'Niger': 'Niger', 'Nigeria': 'Nigeria', 'Nicaragua': 'Nicaragua', 'Netherlands': 'Netherlands', 'Norway': 'Norway', 'Nepal': 'Nepal', 'New Zealand': 'New Zealand', 'Oman': 'Oman', 'Panama': 'Panama', 'Peru': 'Peru', 'Papua New Guinea': 'Papua New Guinea', 'Philippines': 'Philippines', 'Pakistan': 'Pakistan', 'Poland': 'Poland', 'Puerto Rico': 'Puerto Rico', 'West Bank': 'Palestinian Territory', 'Portugal': 'Portugal', 'Paraguay': 'Paraguay', 'Qatar': 'Qatar', 'Romania': 'Romania', 'Republic of Serbia': 'Serbia', 'Russia': 'Russia', 'Rwanda': 'Rwanda', 'Saudi Arabia': 'Saudi Arabia', 'Solomon Islands': 'Solomon Islands', 'Sudan': 'Sudan', 'Sweden': 'Sweden', 'Slovenia': 'Slovenia', 'Slovakia': 'Slovakia', 'Sierra Leone': 'Sierra Leone', 'Senegal': 'Senegal', 'Somalia': 'Somalia', 'Suriname': 'Suriname', 'South Sudan': 'South Sudan', 'El Salvador': 'El Salvador', 'Syria': 'Syrian Arab Republic', 'Swaziland': 'Swaziland', 'Chad': 'Chad', 'French Southern and Antarctic Lands': 'French Southern Territories', 'Togo': 'Togo', 'Thailand': 'Thailand', 'Tajikistan': 'Tajikistan', 'East Timor': 'East Timor', 'Turkmenistan': 'Turkmenistan', 'Tunisia': 'Tunisia', 'Turkey': 'Turkey', 'Trinidad and Tobago': 'Trinidad and Tobago', 'Taiwan': 'Taiwan', 'United Republic of Tanzania': 'Tanzania', 'Ukraine': 'Ukraine', 'Uganda': 'Uganda', 'USA': 'United States of America', 'Uruguay': 'Uruguay', 'Uzbekistan': 'Uzbekistan', 'Venezuela': 'Venezuela', 'Vietnam': 'Vietnam', 'Vanuatu': 'Vanuatu', 'Kosovo': 'Kosovo', 'Yemen': 'Yemen', 'South Africa': 'South Africa', 'Zambia': 'Zambia', 'Democratic Republic of the Congo': 'Zaire', 'Zimbabwe': 'Zimbabwe'}